Signify-epfl/signify-app

app/src/main/java/com/github/se/bootcamp/MainActivity.kt
app/src/main/java/com/github/se/bootcamp/ui/Greeting.kt
app/src/main/java/com/github/se/bootcamp/ui/navigation/BottomNavigationMenu.kt
app/src/main/java/com/github/se/bootcamp/ui/navigation/NavigationActions.kt
app/src/main/java/com/github/se/bootcamp/ui/navigation/Route.kt
app/src/main/java/com/github/se/bootcamp/ui/navigation/Screen.kt
app/src/main/java/com/github/se/bootcamp/ui/navigation/TopLevelDestinations.kt
app/src/main/java/com/github/se/bootcamp/ui/screens/ChallengeScreen.kt
app/src/main/java/com/github/se/bootcamp/ui/screens/MainScreen.kt
app/src/main/java/com/github/se/bootcamp/ui/screens/PracticeScreen.kt
app/src/main/java/com/github/se/bootcamp/ui/screens/ProfileScreem.kt
app/src/main/java/com/github/se/bootcamp/ui/screens/QuestScreen.kt

Added navigation and screens structure for Signify app with updated MainActivity

Samymessouak patch/navigation structure

---

app/src/main/java/com/github/se/bootcamp/MainActivity.kt
app/src/main/java/com/github/se/bootcamp/ui/navigation/BottomNavigationMenu.kt
app/src/main/java/com/github/se/bootcamp/ui/navigation/NavigationActions.kt
app/src/main/java/com/github/se/bootcamp/ui/navigation/Route.kt
app/src/main/java/com/github/se/bootcamp/ui/navigation/Screen.kt
app/src/main/java/com/github/se/bootcamp/ui/navigation/TopLevelDestinations.kt
app/src/main/java/com/github/se/bootcamp/ui/screens/ChallengeScreen.kt
app/src/main/java/com/github/se/bootcamp/ui/screens/LoginScreen.kt
app/src/main/java/com/github/se/bootcamp/ui/screens/PracticeScreen.kt
app/src/main/java/com/github/se/bootcamp/ui/screens/QuestScreen.kt
app/src/main/java/com/github/se/bootcamp/ui/screens/WelcomeScreen.kt

- I created a login and welcome route/screen
- I setup the navigation: welcome -> login -> challenge
- I added button bar for the next screens to implement 
- I created the SignifyAppPreview() in the MainActivity as the main navigation structure for the app (Profile screen and main one not yet complet)
- for the buttomNavMenu just changed the color to match general theme color and added a parameter for for an easier maintenance in the futur  
- for the navigation actions added some functions for better abstraction

Setup the navigation

---

app/src/main/java/com/github/se/bootcamp/MainActivity.kt
app/src/main/java/com/github/se/bootcamp/ui/navigation/Route.kt
app/src/main/java/com/github/se/bootcamp/ui/screens/ProfileScreen.kt
app/src/main/java/com/github/se/bootcamp/ui/screens/SettingsScreen.kt

- adding the implementation to navigate to the setting Screen 
- fist version of the implementation  of the screen

navigation to the settings screen 

---

.github/workflows/CI.yaml
app/src/main/java/com/github/se/signify/MainActivity.kt
app/src/main/java/com/github/se/signify/model/hand/HandLandMarkImplementation.kt
app/src/main/java/com/github/se/signify/model/hand/HandLandMarkRepository.kt
app/src/main/java/com/github/se/signify/model/hand/HandLandMarkViewModel.kt
app/src/main/java/com/github/se/signify/ui/navigation/BottomNavigationMenu.kt
app/src/main/java/com/github/se/signify/ui/navigation/NavigationActions.kt
app/src/main/java/com/github/se/signify/ui/navigation/Route.kt
app/src/main/java/com/github/se/signify/ui/navigation/Screen.kt
app/src/main/java/com/github/se/signify/ui/navigation/TopLevelDestinations.kt
app/src/main/java/com/github/se/signify/ui/screens/ChallengeScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/FriendsListScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/LoginScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/MainScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/PracticeScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/ProfileScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/QuestScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/SettingsScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/WelcomeScreen.kt
app/src/main/res/values/strings.xml

Changed the ci file, for now it only checks the if the code is formated

fix the ci file to match the project name 

---

.github/workflows/CI.yaml

This PR enhances the CI pipeline for the Signify project by introducing several important updates. 
The main change is the integration of Google services by decoding the GOOGLE_SERVICES secret (added securely on GitHub) to generate the google-services.json file during the CI process. This enables Firebase and other Google services to function properly in the build. 
Additional updates include optimizing Gradle caching for faster builds and ensuring compatibility by setting up JDK 17 using the Temurin distribution. 
The pipeline now includes a Kotlin formatting check (ktfmtCheck), builds the debug version of the app, and runs unit tests to ensure reliability.
Instrumentation tests have also been configured to run on an Android emulator with API level 34. 
Finally, JaCoCo has been …

merge the updated ci file 

---

app/src/androidTest/java/com/github/se/signify/ui/screens/LoginScreenTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/WelcomeScreenTest.kt

The implemented test provides 91% line coverage for the WelcomeScreen by verifying both visual elements (the animated image and the welcome text) are correctly rendered when the screen loads.
Additionally, for clarity and consistency, the test file originally named LoginTest has been renamed to LoginScreenTest to better reflect its content and purpose. This change improves code maintainability and readability.

test the welcome screen

---

app/src/androidTest/java/com/github/se/signify/ui/screens/ProfileScreenTest.kt
app/src/main/java/com/github/se/signify/MainActivity.kt
app/src/main/java/com/github/se/signify/Utils.kt
app/src/main/java/com/github/se/signify/ui/navigation/Route.kt
app/src/main/java/com/github/se/signify/ui/screens/MyStatsScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/ProfileScreen.kt
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml

Improving the quality of the code and updating the profile screen to match its new design
Putting the text displayed by the help section in the file strings.xml to avoid hardcoded text
Removing the part about the exercises and questions achieved from the profile screen
Changing the colors used to align with the Figma design
Adding the colors to the file colors.xml to avoid hardcoded colors
Adding a file Utils functions that can be reused in multiple screen to avoid duplication
Creation of the function ReusableButtonWithIcon and ReusableTextButton
In the 4th commit :
adding the tests for the Profile Screen
Adding new file for the Screen MyStats
Implementing the navigation to the new screen from the Profile Screen

Update and test the profile screen

---

.github/workflows/CI.yaml
app/build.gradle.kts
build.gradle.kts

fix the link to sonar as i changed the sonar token

Fix report path

---

app/src/androidTest/java/com/github/se/signify/ui/screens/ExerciseScreenEasyTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/ExerciseScreenHardTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/HomeScreenTest.kt
app/src/main/java/com/github/se/signify/MainActivity.kt
app/src/main/java/com/github/se/signify/ui/navigation/Route.kt
app/src/main/java/com/github/se/signify/ui/screens/Home/ExerciseScreenEasy.kt
app/src/main/java/com/github/se/signify/ui/screens/Home/ExerciseScreenHard.kt
app/src/main/java/com/github/se/signify/ui/screens/Home/HomeScreen.kt

- This PR merges the implementations of the HomeScreen, Exercise Easy, and Exercise Hard features to create a cohesive and functional user experience in the app.
- HomeScreen: Provides the main user interface, displaying various sections like the streak counter, quests button, camera feedback, letter dictionary, and exercise list. It includes navigation to different exercise screens (Easy, Medium, Hard).
- Exercise Easy: Implements the Exercise Easy screen, which offers an introductory level of exercises. The screen is navigable from the HomeScreen and is integrated with all relevant UI components.
- Implements the Exercise Hard screen, which offers a more challenging set of exercises. Similar to Exercise Easy, it is accessible from the HomeScreen.
- Integrated navigation between …

Merge between different pull requests to get a valid final app

---

app/src/main/java/com/github/se/signify/model/user/SaveUserToFireStore.kt
app/src/main/java/com/github/se/signify/model/user/User.kt
app/src/main/java/com/github/se/signify/model/user/UserRepository.kt
app/src/main/java/com/github/se/signify/model/user/UserRepositoryFireStore.kt
app/src/main/java/com/github/se/signify/model/user/UserViewModel.kt
app/src/test/java/com/github/se/signify/model/user/SaveUserToFireStoreTest.kt
app/src/test/java/com/github/se/signify/model/user/UserRepositoryFireStoreTest.kt
app/src/test/java/com/github/se/signify/model/user/UserViewModelTest.kt

**Additions** 
- Create a collection in FireStore to save the user's informations.
- Create the User Repository interface.
- Implement the Firestore Repository
- Create the User ViewModel
- Test the code with unit tests 
**Next steps**
- Use the implemented functions in the FriendListScreen to offer the possibility to send requests to friends and add them.
- Manage other user data such as their profile photo in the Settings Screen.

Create a database for the users, create and implement the FireStore Repository

---

app/src/androidTest/java/com/github/se/signify/ui/screens/ChallengeHistoryScreenTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/ChallengeScreenTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/NewChallengeScreenTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/ProfileScreenTest.kt

- Improved set up of the tests instead of setting the content multiple time in each test

Reduce duplication on the test for the setup

---

app/src/androidTest/java/com/github/se/signify/ui/screens/FriendsListScreenTest.kt

**Pull Request Description:**
This pull request introduces Android tests for the `FriendsListScreen.kt` component. The tests aim to enhance test coverage and ensure that the UI behaves as expected. It is linked to the issue #106 .
- Created a new test file `FriendsListScreenTest.kt` located in the appropriate test directory.
- Implemented the following tests:
- **Display Tests**: Verifies that the Friends List and Friend Requests are displayed correctly.
- **Navigation Test**: Confirms that pressing the back button navigates to the profile screen.
- Improves the reliability of the `FriendsListScreen` by ensuring that key functionalities are tested.
- Increases overall test coverage for the UI components.
- Tests can be run using the standard Android testing framework.
- All tests have …

test: add Android tests for FriendsListScreen.kt

---

app/src/main/java/com/github/se/signify/MainActivity.kt
app/src/main/java/com/github/se/signify/ui/Utils.kt
app/src/main/java/com/github/se/signify/ui/navigation/BottomNavigationMenu.kt
app/src/main/java/com/github/se/signify/ui/screens/Profile/FriendsListScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/Profile/ProfileScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/Profile/SettingsScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/challenge/ChallengeHistoryScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/challenge/ChallengeScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/challenge/NewChallengeScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/home/ASLRecognition.kt
app/src/main/java/com/github/se/signify/ui/screens/home/ExerciseScreenEasy.kt
app/src/main/java/com/github/se/signify/ui/screens/home/ExerciseScreenHard.kt
app/src/main/java/com/github/se/signify/ui/screens/profile/SettingsScreen.kt

I have gone through all UI source code files and fixed most of the straightforward warnings Android Studio highlights there.
This should lower the issue count in SonarCloud.
I had to leave some more complex warnings, that I couldn't fix quickly, with my limited understanding of some files.
This should be a rather safe PR to approve assuming it passes CI.
For all future push requests, we should avoid merging anything that raises warnings on either Android Studio or SonarCloud.

Address all android studio warnings on UI code

---

app/src/androidTest/java/com/github/se/signify/ui/screens/HomeScreenTest.kt
app/src/main/java/com/github/se/signify/ui/Utils.kt
app/src/main/java/com/github/se/signify/ui/screens/home/HomeScreen.kt

This pull request introduces several key changes to improve the usability and reduce code duplication in the HomeScreen:
1. **Add Scrolling Feature for Letter Dictionary:**
- Implemented a scrollable Letter Dictionary.
- Added functionality to cycle through letters from 'a' to 'z' using left and right arrow buttons.
- Wrapped the letter and associated gesture in state to enable the navigation.
- Created `getLetterIconResId()` utility function to map each letter to its respective drawable resource.
2. **Unit Tests for Scrolling Feature:**
- Added unit tests to verify that the correct letter and gesture icon are displayed after each arrow click.
- Added test tags to the Letter Dictionary composables for better testability.
3. **Refactored Util Buttons:**
- Replaced the following buttons …

Implement home screen letter dictionary

---

app/build.gradle.kts
build.gradle.kts
sonar-project.properties

This is a fix for the gradle app as i forgot to remove the previous sonar job

116 link the jacoco report to sonarcloud

---

app/src/androidTest/java/com/github/se/signify/ui/screens/challenge/ChallengeHistoryScreenTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/challenge/ChallengeScreenTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/challenge/NewChallengeScreenTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/home/ExerciseScreenEasyTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/home/ExerciseScreenHardTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/home/HomeScreenTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/profile/FriendsListScreenTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/profile/ProfileScreenTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/profile/SettingsScreenTest.kt

- The test folder has been organized to mirror the main source code package structure. This improves readability and maintainability, allowing developers to easily find corresponding test cases for each source file.

impove readability of code by classifying/merging to particular packages

---

.gitattributes
app/.gitignore
app/src/main/assets/RFC_model_ir9_opset19.onnx

- Changed the .gitignore to be able to push the RFC_model
- Push RFC_model using LFS file

Add RFC model using Git LFS

---

.gitattributes
app/.gitignore
app/build.gradle.kts
app/src/main/assets/RFC_model_ir9_opset19.onnx
app/src/test/java/com/github/se/signify/model/hand/HandLandMarkViewModelTest.kt

- Formatting files & creating the tests using mockito 
- Remoove duplicates in the build.gradle.kts 
Future work : Add tests for HandLandMarkImplementation

Add test to HandLandMarkViewModel to upgrade the coverage.

---

app/src/androidTest/java/com/github/se/signify/ui/screens/home/ASLRecognitionTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/home/HandLandMarkImplementationInstrumentedTest.kt
app/src/main/java/com/github/se/signify/model/hand/HandLandMarkImplementation.kt
app/src/main/java/com/github/se/signify/ui/screens/home/ASLRecognition.kt

- Added testags related to the UI tests in ASLRecognitionTest
- Write a class test named ASLRecognitionTest that check if the components are all displayed -> achieved 84% coverage
- Changed "HandLandmarker" from lateinit var to simply var.
Here is the coverage report :

Add UI test for ASLRecognition and achieve 84% coverage

---

app/src/androidTest/java/com/github/se/signify/ui/screens/MainActivityTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/profile/MyStatsScreenTest.kt
app/src/main/java/com/github/se/signify/MainActivity.kt
app/src/main/java/com/github/se/signify/model/challenge/Challenge.kt
app/src/main/java/com/github/se/signify/model/challenge/ChallengeRepository.kt
app/src/main/java/com/github/se/signify/model/challenge/ChallengeRepositoryFireStore.kt
app/src/main/java/com/github/se/signify/model/challenge/ChallengeViewModel.kt
app/src/main/java/com/github/se/signify/model/user/SaveUserToFireStore.kt
app/src/main/java/com/github/se/signify/model/user/User.kt
app/src/main/java/com/github/se/signify/model/user/UserRepository.kt
app/src/main/java/com/github/se/signify/model/user/UserRepositoryFireStore.kt
app/src/main/java/com/github/se/signify/model/user/UserViewModel.kt
app/src/main/java/com/github/se/signify/ui/Utils.kt
app/src/main/java/com/github/se/signify/ui/navigation/BottomNavigationMenu.kt
app/src/main/java/com/github/se/signify/ui/navigation/Route.kt
app/src/main/java/com/github/se/signify/ui/screens/challenge/CreateAChallengeScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/challenge/NewChallengeScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/home/ASLRecognition.kt
app/src/main/java/com/github/se/signify/ui/screens/profile/FriendsListScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/profile/MyStatsScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/profile/ProfileScreen.kt

Since I've only addressed code warnings, this should be a simple PR to review.
I've gone over the remaining SonarCloud issues on UI source code, hoping all of them go away.
None of these refactors should meaningfully alter the product.

Address sonarcloud issues on UI code

---

app/src/test/java/com/github/se/signify/model/challenge/ChallengeRepositoryFireStoreTest.kt
app/src/test/java/com/github/se/signify/model/challenge/ChallengeTest.kt
app/src/test/java/com/github/se/signify/model/challenge/ChallengeViewModelTest.kt
app/src/test/java/com/github/se/signify/model/user/SaveUserToFireStoreTest.kt
app/src/test/java/com/github/se/signify/model/user/UserRepositoryFireStoreTest.kt
app/src/test/java/com/github/se/signify/model/user/UserViewModelTest.kt

This pull request involves implementing and verifying comprehensive test cases to ensure the robustness and correctness of the new challenge collection in Firestore.
* Added comprehensive test coverage to ensure the functionality and reliability of challenge-related features.
* Validated integration with Firestore and ensured data consistency across operations.
- **ChallengeRepositoryFirestore Tests**
* Developed tests to validate the integration with the challenge collection.
* Ensured that challenge creation and deletion functionalities operate seamlessly.
- **ChallengeViewModel Tests**
* Implemented tests for view-model logic.
* Verified proper handling of challenge lifecycle operations, including creating and deleting challenges.
* Confirmed real-time updates with Firestore.
- …

Comprehensive Testing for Challenge Collection in Firestore

---

app/src/androidTest/java/com/github/se/signify/ui/screens/home/HandLandMarkImplementationInstrumentedTest.kt
app/src/main/java/com/github/se/signify/model/hand/HandLandMarkImplementation.kt

Improve test coverage for HandLandmarkImplementation; adjust landmark rotation logic for ONNX model compatibility
- Added imports and unit tests to increase coverage of HandLandmarkImplementation
- Refined landmark rotation logic: fixed axis mapping and orientation
Simple PR with a simple review

fix: the output of the letter and updated tests for HandLandMarkImplementation 

---

app/src/androidTest/java/com/github/se/signify/ui/screens/UtilsTest.kt
app/src/main/java/com/github/se/signify/ui/Utils.kt
app/src/main/java/com/github/se/signify/ui/screens/challenge/ChallengeScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/profile/ProfileScreen.kt

This PR refactors the `SquareButton()` function in `Utils.kt` to comply with SonarCloud’s code quality guidelines, specifically the limit on the number of parameters a function can have. The function previously accepted more than 7 parameters, which raised an issue in SonarCloud for code complexity. Related to the task #204 .
- Reduced the number of parameters in `SquareButton()` by setting default values where applicable and grouping others.
- Updated all references to `SquareButton()` across the codebase to align with the new function signature.
- Refactor documentation to clarify usage of the modified `SquareButton()` function.
This refactor improves code readability and maintainability by simplifying the function’s parameter structure. It addresses the SonarCloud code quality issue …

SquareButton() refactor

---

app/src/test/java/com/github/se/signify/model/quest/QuestRepositoryFirestoreTest.kt

This pull request introduces major enhancements and increased test coverage for the `QuestRepositoryFireStore` class.
1. **Increased Test Coverage**:
- Achieved a coverage increase from 62% to 86% by adding targeted tests for all branches and handling various edge cases in `getDailyQuest`.
- Expanded `documentToQuest` tests to confirm correct behavior when fields are missing, returning `null`, or causing exceptions.
2. **Comprehensive Tests for `getDailyQuest`**:
- **Success Scenarios**: Added tests to confirm that quests are consistently sorted in ascending order by index, covering cases like non-sequential indices, duplicate values, and negative values.
- **Failure Scenarios**: Simulated multiple failure conditions, including an empty document list, `null` task results, and Firestore …

Improved Test Coverage and Robustness for QuestRepositoryFireStore

---

app/src/androidTest/java/com/github/se/signify/ui/screens/challenge/CreateAChallengeScreenTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/challenge/NewChallengeScreenTest.kt

* After the valuable feedback from my coaches, I realized the importance of combining feature and test code in a single PR. This helps maintain clarity, context, and better review practices.
* Moving forward, I will ensure not to push tests alone without their associated features.
This pull request introduces comprehensive UI and functionality tests for the **NewChallengeScreen** and **CreateAChallengeScreen**. These tests validate the robustness of user interactions and ensure seamless integration with Firestore.
This task focused on validating the functionality and design of the revamped **NewChallengeScreen**, ensuring a seamless user experience and robust Firestore integration. The tests included:
- **Challenge Deletion**: Unit tests to verify the successful deletion of challenges …

Added two new challenges class test to improve test coverage

---

app/src/main/java/com/github/se/signify/ui/screens/home/ASLRecognition.kt
app/src/main/java/com/github/se/signify/ui/screens/home/ExerciseScreenEasy.kt

- Changed the form black to white in ExerciseCommon
- Changed the background of topappbar in ASLRecognition for a better common UI

fix: corrected colors in ASLRecognition and ExerciseCommon

---

app/build.gradle.kts
app/src/androidTest/java/com/github/se/signify/ui/screens/MainActivityTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/profile/FriendsListScreenTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/profile/ProfileScreenTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/profile/SettingsScreenTest.kt
app/src/main/java/com/github/se/signify/model/user/UserRepository.kt
app/src/main/java/com/github/se/signify/model/user/UserRepositoryFireStore.kt
app/src/main/java/com/github/se/signify/model/user/UserViewModel.kt
app/src/main/java/com/github/se/signify/ui/screens/profile/FriendsListScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/profile/MyStatsScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/profile/ProfileScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/profile/SettingsScreen.kt
app/src/test/java/com/github/se/signify/model/user/FireBaseStorageTest.kt
app/src/test/java/com/github/se/signify/model/user/UserRepositoryFireStoreTest.kt
app/src/test/java/com/github/se/signify/model/user/UserViewModelTest.kt
gradle/libs.versions.toml

**Feature: Integrate Firebase Storage for User Profile Pictures**
---
This pull request integrates Firebase Storage for managing user profile pictures, replacing the previous local storage approach. This update requires an **updated version of the `google-services.json` file** to ensure compatibility with Firebase Storage.
1. **Updated Functionality**:
- Modified the function `updateProfilePictureUrl` in the following files:
- `UserViewModel`
- `UserRepository`
- `UserRepositoryFireStore`
- Changed the type of `newProfilePictureUrl` from `String?` to `Uri?`.
- Implemented Firebase Storage integration for storing profile pictures.
2. **Real-Time Updates**:
- Added a `LaunchedEffect` in the screens under the `profile` folder to ensure the profile picture updates in real time when changed. …

Update profile picture

---

app/src/androidTest/java/com/github/se/signify/ui/screens/profile/FriendsListScreenTest.kt
app/src/main/java/com/github/se/signify/model/user/UserViewModel.kt
app/src/main/java/com/github/se/signify/ui/screens/profile/FriendsListScreen.kt

This small PR resolves the bug where the 'User not found' error message was always displayed in the FriendsListScreen. Additionally, several improvements have been implemented to enhance the user experience and functionality of the screen.
_____
1. **Bug Fix**:  
- Introduced a new \`errorState\` variable in the \`UserViewModel\` class to handle and display error messages dynamically.  
2. **UI Improvements**:  
- Fixed the color of the search bar for better visibility and aesthetic appeal.  
- Added toast messages to provide feedback when:  
- A user sends a friend request.  
- A user removes a friend they searched for.  
3. **Enhanced Search Functionality**:  
- Displayed the profile picture of the user being searched.  
- Added a button to allow users to navigate to their own profile …

Update friends list screen

---

README.md
app/build.gradle.kts
app/src/androidTest/java/com/github/se/signify/ui/screens/LoginScreenTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/MainActivityTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/UtilsTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/challenge/ChallengeScreenTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/home/FeedbackScreenTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/home/QuestScreenTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/home/QuizScreenTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/profile/FriendsListScreenTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/profile/ProfileScreenTest.kt
app/src/androidTest/java/end2end/MainToASLRecognitionTest.kt
app/src/main/AndroidManifest.xml
app/src/main/java/com/github/se/signify/ui/Utils.kt
app/src/main/java/com/github/se/signify/ui/screens/LoginScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/challenge/ChallengeScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/home/FeedbackScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/home/QuestScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/home/QuizScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/profile/ProfileScreen.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/network_security_config.xml

- This PR includes updates to address dependencies issues, introduces an offline mode feature, adds tests, and creates the first end-to-end test for the app.
- Updated the build.gradle.kts to resolve dependency issues preventing the usage of createAndroidComposeRule for UI tests. - The issue was related to protobuf-related dependencies.
- Implemented an offline mode where only the "Practice Epic" is accessible.
- All other user-related screens display a white screen prompting the user to log in to continue.
- The white offline screen utilizes common elements from the utils package for consistent UI design.
- Added unit tests for the white offline screen to verify the displayed elements and functionality.
- Added the first end-to-end test, which navigates from the app's start to the ASL …

feat: add end2end tests for practice epic

---

app/src/main/java/com/github/se/signify/model/stats/MockStatsRepository.kt
app/src/test/java/com/github/se/signify/model/stats/MockStatsRepositoryTest.kt
app/src/test/java/com/github/se/signify/model/stats/StatsViewModelTest.kt

---
This PR introduces and integrates a new `MockStatsRepository` to streamline testing for `StatsViewModel`. The following updates are included:
---
The `MockStatsRepository` serves as testable substitute for the actual `StatsRepository`. Key features include:
- **Method Call Verification**:  
- Tracks method calls using `trackCall` and stores them in an internal list.  
- `wasMethodCalled(String)` verifies if a specific method was invoked.  
- `getMethodCalls()` provides a complete list of invoked methods.  
- **Argument Tracking**:  
- Tracks arguments passed to methods through generic lambdas (`getStat` and `updateStat`).  
- Introduced a `shouldSucceed` flag to simulate repository behavior:  
- On success (`shouldSucceed = true`), operations invoke success callbacks with expected …

Mock stats repository

---

app/build.gradle.kts
app/src/test/java/com/github/se/signify/model/user/UserRepositoryFireStoreTest.kt
app/src/test/java/com/github/se/signify/model/user/UserViewModelTest.kt
gradle/libs.versions.toml

The goal of this pull request is to increase the test coverage for `UserViewModel` and `UserRepositoryFireStore`. The initial line coverage for both classes was approximately **60%**. By adding extensive tests, particularly focusing on failure cases and edge scenarios.
- **Added Tests for Success Cases:**
- Verified that the `MutableStateFlow` properties are correctly updated on successful repository callbacks.
- Ensured methods like `getUserById`, `getUserName`, `getProfilePictureUrl`, and `getOngoingChallenges` handle successful responses appropriately.
- **Added Tests for Failure Cases:**
- Simulated exceptions and repository failures to test how the `UserViewModel` handles errors.
- Verified that error states are correctly set and internal states remain consistent when failures occur. …

Increase Test Coverage for UserViewModel and UserRepositoryFireStore

---

app/src/androidTest/java/com/github/se/signify/ui/screens/home/ExerciseScreenTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/home/HomeScreenTest.kt
app/src/main/java/com/github/se/signify/MainActivity.kt
app/src/main/java/com/github/se/signify/model/exercise/ExerciseLevel.kt
app/src/main/java/com/github/se/signify/ui/screens/home/ExerciseScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/home/HomeScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/profile/MyStatsScreen.kt

In this PR, I added the update call for the statistic after the user finish an exercise.
Related issues: #311 .
- Call of the function `updateEasyExerciseStats()`, `updateMediumExerciseStats()` and `updateHardExerciseStats()` when the corresponding exercise difficulty is completed.
- Rename the val `levelName` to `id` and the val `levelScreen` to `screen` in order to have understandable call from ExerciseLevel as asked by @ThomasMPont in my previous PR.
- Added the call of the getter function in MyStatsScreen. This part took me some time as I had difficutly to understand why the update weren't displayed in the screen, but the change were correctly done in firebase until I remarked that these call were missing in order to track changes made to firebase.
- There is no added test for this …

Statistics update for exercise

---

app/src/main/java/com/github/se/signify/ui/screens/WelcomeScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/auth/LoginScreen.kt

The text in french mode was not shown correctly due to it's length.
Changes : increased from 200 to 300.dp

fix: increased size of the Welcome text in LoginScreen.kt

---

app/src/androidTest/java/com/github/se/signify/ui/screens/challenge/ChallengeHistoryScreenTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/challenge/ChronoChallengeGameScreenTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/challenge/NewChallengeScreenTest.kt
app/src/main/java/com/github/se/signify/MainActivity.kt
app/src/main/java/com/github/se/signify/model/challenge/Challenge.kt
app/src/main/java/com/github/se/signify/model/challenge/ChallengeRepository.kt
app/src/main/java/com/github/se/signify/model/challenge/FirestoreChallengeRepository.kt
app/src/main/java/com/github/se/signify/model/challenge/MockChallengeRepository.kt
app/src/main/java/com/github/se/signify/model/common/user/FirestoreUserRepository.kt
app/src/main/java/com/github/se/signify/model/common/user/MockUserRepository.kt
app/src/main/java/com/github/se/signify/model/common/user/SaveUserToFirestore.kt
app/src/main/java/com/github/se/signify/model/common/user/User.kt
app/src/main/java/com/github/se/signify/model/common/user/UserRepository.kt
app/src/main/java/com/github/se/signify/model/common/user/UserViewModel.kt
app/src/main/java/com/github/se/signify/ui/screens/challenge/ChallengeHistoryScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/challenge/ChronoChallengeGameScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/challenge/CreateAChallengeScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/challenge/NewChallengeScreen.kt
app/src/main/res/values-fr/strings.xml
app/src/main/res/values/strings.xml
app/src/test/java/com/github/se/signify/model/challenge/ChallengeTest.kt
app/src/test/java/com/github/se/signify/model/challenge/FirestoreChallengeRepositoryTest.kt
app/src/test/java/com/github/se/signify/model/challenge/MockChallengeRepositoryTest.kt
app/src/test/java/com/github/se/signify/model/common/user/FirestoreUserRepositoryTest.kt
app/src/test/java/com/github/se/signify/model/common/user/MockUserRepositoryTest.kt
app/src/test/java/com/github/se/signify/model/common/user/UserViewModelTest.kt

This pull request addresses several updates and enhancements to the challenge feature and user stats tracking in the Signify application. Below is a detailed summary of the changes:
- Added necessary strings to support the redesigned Challenge History Screen.
- Introduced a `winner` field to the challenge model.
- Implemented the `updateWinner` function to determine and store the winner of a challenge.
- Modified the user model to include fields for challenge statistics:
- Challenges created.
- Challenges completed.
- Challenges won.
- Added functions to retrieve and manipulate these fields.
- Developed extensive tests for the newly added functions in the user model to maintain robustness.
- Updated the game logic to allow gameplay for both players, ensuring an engaging and fair …

Fix challenge and implement history challenge screen logic

---

app/src/androidTest/java/com/github/se/signify/end2end/HomeScreenFeaturesEnd2endTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/home/HomeScreenTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/tutorial/HighlightAreaTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/tutorial/ProvideElementPositionsTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/tutorial/TutorialOverlayTest.kt
app/src/androidTest/java/com/github/se/signify/ui/screens/tutorial/TutorialScreenTest.kt
app/src/main/java/com/github/se/signify/MainActivity.kt
app/src/main/java/com/github/se/signify/model/navigation/Screen.kt
app/src/main/java/com/github/se/signify/ui/common/Practice.kt
app/src/main/java/com/github/se/signify/ui/screens/auth/LoginScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/home/HomeScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/tutorial/ElementPosition.kt
app/src/main/java/com/github/se/signify/ui/screens/tutorial/HighlightedArea.kt
app/src/main/java/com/github/se/signify/ui/screens/tutorial/TutorialOverlay.kt
app/src/main/java/com/github/se/signify/ui/screens/tutorial/TutorialScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/tutorial/TutorialStep.kt
app/src/main/res/values-fr/strings.xml
app/src/main/res/values/strings.xml

This PR completes the implementation of the Tutorial Screen for the Home Screen, ensuring compatibility with all screen sizes and aspect ratios. The primary addition is using `onGloballyPositioned` to dynamically detect element positions, allowing the tutorial to be displayed correctly across various devices. Additionally, several improvements were made to enhance the structure, usability, and maintainability of the tutorial logic.
1. **Position Detection for Tutorial Elements**:
- Added `ElementPosition.kt` to detect element positions using `onGloballyPositioned` with `CompositionLocalProvider`.
- Updated `HomeScreen.kt` and `MainActivity.kt` to integrate position detection.
2. **Tutorial Screen Enhancements**:
- Redesigned the tutorial logic to organize steps into a list using a new …

Finish the implementation of the Tutorial for the Home Screen

---

app/src/androidTest/java/com/github/se/signify/ui/screens/home/QuestScreenTest.kt
app/src/main/java/com/github/se/signify/model/dependencyInjection/MockDependencyProvider.kt
app/src/main/java/com/github/se/signify/model/home/quest/MockQuestRepository.kt
app/src/test/java/com/github/se/signify/model/home/quest/MockQuestRepositoryTest.kt

<html>
<body>
<hr>
<h2><strong>Pull Request Title</strong></h2>
<p><strong>Add MockQuestRepository and Integrate for Testing Quest Screens</strong></p>
<hr>
<h2><strong>Description</strong></h2>
<h3>What was done:</h3>
<ol>
<li>
<p><strong>Implemented <code inline="">MockQuestRepository</code></strong>:</p>
<ul>
<li>Simulates the <code inline="">QuestRepository</code> for testing purposes.</li>
<li>Pre-populated with two mock <code inline="">Quest</code> items: "Hello" and "Goodbye".</li>
<li>Includes the ability to simulate success (<code inline="">succeed()</code>) and failure (<code inline="">fail()</code>).</li>
</ul>
</li>
<li>
<p><strong>Added Unit Tests for <code inline="">MockQuestRepository</code></strong>:</p>
<ul>
<li>Verified successful quest retrieval.</li>
<li>Tested failure …

Mock the Quest Repository

---

app/src/androidTest/java/com/github/se/signify/end2end/HomeScreenFeaturesEnd2endTest.kt
app/src/androidTest/java/com/github/se/signify/model/home/quiz/MockQuizRepositoryTest.kt
app/src/main/java/com/github/se/signify/model/dependencyInjection/MockDependencyProvider.kt
app/src/main/java/com/github/se/signify/model/home/quiz/MockQuizRepository.kt
app/src/main/java/com/github/se/signify/ui/screens/home/QuizScreen.kt

- This PR introduces a MockQuizRepository implementation and corresponding unit tests to enhance the end-to-end (E2E) testing capabilities for the HomeScreen feature. Previously, the E2E test assumed the quiz would automatically be solved without simulating user actions, such as selecting an answer and clicking the submit button. By mocking the QuizRepository, we enable controlled, predictable behavior during tests, allowing for accurate simulation of user interactions.
1. MockQuizRepository Implementation:
- Provides a simple mocked quiz question with predefined data ("apple" as the correct answer with signs and confusers).
Includes methods to simulate success or failure scenarios, making it easier to test edge cases.
2. MockQuizRepositoryTest Unit Tests:
- Verifies that the repository …

feat: mocked QuizRepository and update end2end test Accordingly i.e solve the quiz

---

app/src/main/java/com/github/se/signify/ui/screens/home/ExerciseScreen.kt

Repeated letters were being processed immediately in the exercise screens. 
- Fixed the issue in the **exercise screens**:
- Added a **cooldown mechanism** in the `onProgressUpdate` function.
- Temporarily pauses gesture checking for a short duration after a successful match.
- Ensures smoother gesture processing and prevents unintended rapid progressions.
I wasn't able to get my camera to work on the emulator on mac. As such I have carefully mocked the camera behaviour and update of the detectedGesture variable, was able to recreate the issue and fix it. I would still like as a sanity check for someone able to use his cam to quickly confirm correct behaviour.
- As the logic in challenges was not the same as in exercises, I had some trouble implementing the fix. What remains is to include …

Add cooldown mechanism to prevent rapid gesture detection in exerciseScreens

---

app/src/androidTest/java/com/github/se/signify/ui/screens/challenge/SprintChallengeGameScreenTest.kt
app/src/main/java/com/github/se/signify/ui/screens/challenge/NewChallengeScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/challenge/SprintChallengeGameScreen.kt

The PR got hardcoded strings which break the switch language feature.

Revert "Skip button in sprint mode "

---

app/src/androidTest/java/com/github/se/signify/ui/screens/challenge/SprintChallengeGameScreenTest.kt
app/src/main/java/com/github/se/signify/ui/screens/challenge/NewChallengeScreen.kt
app/src/main/java/com/github/se/signify/ui/screens/challenge/SprintChallengeGameScreen.kt

Reverts Signify-epfl/signify-app#481

Revert "Revert "Skip button in sprint mode ""

---

app/src/main/java/com/github/se/signify/ui/common/Statistics.kt

This PR updates the streak counter's color to align with the primary color of the application, ensuring a more cohesive design and improved visual consistency across the app. Additionally, the Figma design has been updated to reflect this change for accurate design-to-development alignment.
- **Streak Counter Color Update**:
- Changed the streak counter color to use the application's primary color (`MaterialTheme.colorScheme.primary`).
- Ensured the new color integrates seamlessly with the overall app theme.
- **Figma Design Update**:
- Updated the Figma design file to reflect the new streak counter color, ensuring that the design and implementation remain consistent.
- Improved visual coherence by matching the streak counter to the app's primary color palette.
- Ensures that the …

Changed flame color after updating figma

---

app/build.gradle.kts
app/src/androidTest/java/com/github/se/signify/ui/screens/home/ExerciseScreenTest.kt
app/src/main/java/com/github/se/signify/model/common/Utils.kt
app/src/main/java/com/github/se/signify/model/home/exercise/ExerciseLevel.kt
app/src/main/java/com/github/se/signify/model/profile/stats/FirestoreStatsRepository.kt
app/src/main/java/com/github/se/signify/model/profile/stats/MockStatsRepository.kt
app/src/main/java/com/github/se/signify/model/profile/stats/SaveStatsToFirestore.kt
app/src/main/java/com/github/se/signify/model/profile/stats/Stats.kt
app/src/main/java/com/github/se/signify/model/profile/stats/StatsRepository.kt
app/src/main/java/com/github/se/signify/model/profile/stats/StatsViewModel.kt
app/src/main/java/com/github/se/signify/ui/screens/home/ExerciseScreen.kt
app/src/main/res/values-fr/strings.xml
app/src/main/res/values/strings.xml
app/src/test/java/com/github/se/signify/model/common/UtilsTest.kt
app/src/test/java/com/github/se/signify/model/profile/stats/FirestoreStatsRepositoryTest.kt
app/src/test/java/com/github/se/signify/model/profile/stats/MockStatsRepositoryTest.kt
app/src/test/java/com/github/se/signify/model/profile/stats/StatsTest.kt
app/src/test/java/com/github/se/signify/model/profile/stats/StatsViewModelTest.kt
gradle/libs.versions.toml

Reverts Signify-epfl/signify-app#400

Revert "Find a way to track time during exercise"
