README.md
Add specifications on how developers should go about creating and updating scrum board tasks to the project's README.md.
=> Specify a procedure for handling scrum board tasks

.github/workflows/CI.yaml, app/build.gradle.kts, app/src/main/java/com/github/se/signify/MainActivity.kt, app/src/main/java/com/github/se/signify/model/hand/HandLandMarkImplementation.kt, app/src/main/java/com/github/se/signify/model/hand/HandLandMarkRepository.kt, app/src/main/java/com/github/se/signify/model/hand/HandLandMarkViewModel.kt, app/src/main/java/com/github/se/signify/ui/navigation/BottomNavigationMenu.kt, app/src/main/java/com/github/se/signify/ui/navigation/NavigationActions.kt, app/src/main/java/com/github/se/signify/ui/navigation/Route.kt, app/src/main/java/com/github/se/signify/ui/navigation/Screen.kt, app/src/main/java/com/github/se/signify/ui/navigation/TopLevelDestinations.kt, app/src/main/java/com/github/se/signify/ui/screens/ChallengeScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/FriendsListScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/LoginScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/MainScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/PracticeScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/ProfileScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/QuestScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/SettingsScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/WelcomeScreen.kt, app/src/main/java/com/github/se/signify/ui/theme/Color.kt, app/src/main/java/com/github/se/signify/ui/theme/Theme.kt, app/src/main/java/com/github/se/signify/ui/theme/Type.kt, settings.gradle.kts
Replaced all instances of the word 'bootcamp' with 'signify' across the project to align with the new project name and branding. This includes changes in code comments, variable names, function names, documentation, and any other relevant occurrences where 'bootcamp' was used.
=> Replace all the occurences of 'bootcamp' with 'signify'

README.md
Remove scrum task instructions section from README.md after moving them to this repository's wiki, as suggested by the coaches.
=> Move scrum task instructions from README.md to wiki

app/src/androidTest/java/com/github/se/signify/ui/screens/ChallengeHistoryScreenTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/ChallengeScreenTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/ExerciseScreenEasyTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/ExerciseScreenHardTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/HomeScreenTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/NewChallengeScreenTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/ProfileScreenTest.kt, app/src/main/java/com/github/se/signify/MainActivity.kt, app/src/main/java/com/github/se/signify/ui/screens/challenge/ChallengeHistoryScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/challenge/ChallengeScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/challenge/NewChallengeScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/home/ASLRecognition.kt, app/src/main/java/com/github/se/signify/ui/screens/home/ExerciseScreenEasy.kt, app/src/main/java/com/github/se/signify/ui/screens/home/ExerciseScreenHard.kt, app/src/main/java/com/github/se/signify/ui/screens/home/HomeScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/home/QuestScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/profile/FriendsListScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/profile/MyStatsScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/profile/ProfileScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/profile/SettingsScreen.kt
I've renamed screen packages (Challenge, Home, Profile) to not be capitalized, as required by Kotlin conventions.
This is a simple but broad refactor, that should be approved asap to avoid merge conflicts.
=> Rename screen packages to be lowercase

README.md, app/.gitignore
I added the figma link for the M1 in the README.md file.
As the "app/src/main/assets/RFC_model_ir9_opset19.onnx" file is too big to be push by git I added it in the gitignore.
This PR is related to task #103
=> docs: add Figma M1 file link to README.md

app/src/androidTest/java/com/github/se/signify/ui/screens/SettingsScreenTest.kt
**Pull Request Description:**
This pull request adds Android tests for the `SettingsScreen.kt` component. The new tests are designed to improve test coverage and verify the correct functionality of the settings screen. It is link to the issue #110 .
- Created a new test file `SettingsScreenTest.kt` in the appropriate test directory.
- Implemented the following tests:
- **Display Tests**: Ensures that the username, edit icons, and other settings are displayed correctly.
- **Back Navigation Test**: Confirms that clicking the back button triggers the expected navigation.
- **Edit Username Click Test**: Verifies that the editable username is clickable.
- **Cancel Button Test**: Checks the behavior when the cancel button is clicked (implementation pending).
- **Save Button Test**: Verifies the …
=> test: add Android tests for SettingsScreen.kt

app/build.gradle.kts
This PR adds the necessary configuration for generating a signed APK for the app, including setting up the keystore and key credentials in the `build.gradle` file. It also integrates Firebase by adding the SHA-1 and SHA-256 fingerprints to enable Google Authentication in the release build.
- Configured the `signingConfigs` block in `build.gradle` to reference the release keystore (`signify.jks`).
- Added store and key credentials to sign the APK with the release key.
- Verified that the SHA-1 and SHA-256 fingerprints for the release key are added to Firebase.
- Downloaded the updated `google-services.json` file from Firebase to ensure that the release build is correctly integrated with Google services.
- Verified that Google Authentication works in both debug and release builds.
1. Run …
=> Configure release signing and integrate Firebase SHA-1 for Google Auth

app/build.gradle.kts, build.gradle.kts, sonar-project.properties
Previously, the **SonarQube configuration** block was located at the end of the `build.gradle.kts` file, outside the main `android` configuration. I moved the **SonarQube configuration** into the correct location within the `android` block to ensure that it is properly integrated and applied during the build process. This change aligns the SonarQube setup with the rest of the project configurations.
The **`sonar.coverage.jacoco.xmlReportPaths`** property in the SonarQube configuration was updated. Initially, it did not include the **`jacocoTestReport`** folder in the path, which resulted in incorrect report generation.
This ensures that the correct Jacoco test report is generated and included in the SonarQube analysis.
I also did additional work on configuring **SonarCloud** integration, …
=> Fix the path to jacoco report for sonarcloud

app/src/androidTest/java/com/github/se/signify/ui/screens/MainActivityTest.kt, app/src/main/java/com/github/se/signify/MainActivity.kt, app/src/main/java/com/github/se/signify/ui/screens/LoginScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/WelcomeScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/challenge/ChallengeHistoryScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/challenge/NewChallengeScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/home/ExerciseScreenEasy.kt, app/src/main/java/com/github/se/signify/ui/screens/home/ExerciseScreenHard.kt, app/src/main/java/com/github/se/signify/ui/screens/home/HomeScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/home/QuestScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/profile/FriendsListScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/profile/MyStatsScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/profile/ProfileScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/profile/SettingsScreen.kt
- Added MainActivityTest that basically go trough different screens from SignifyAppPreview and check if that's the case.
- Changed the composable functions of different screen to add testtags important for testing.
- Changed Reference of SignifyAppPreview to receive context & navigationActions in order to test
- Achieved 73% coverage :
- And finally we achieved 80% for all the app :
=> Add MainActivityTest to test the MainActivity for higher coverage (80%)

app/src/androidTest/java/com/github/se/signify/ui/screens/home/ASLRecognitionTest.kt, app/src/main/java/com/github/se/signify/model/hand/HandLandMarkImplementation.kt, app/src/main/java/com/github/se/signify/model/hand/HandLandMarkViewModel.kt, app/src/main/java/com/github/se/signify/ui/screens/home/ASLRecognition.kt, app/src/main/res/values/strings.xml
- Added the necessary imports such as Intent & Uri
-  added a constant value that contains the Uri to the webpage
- link the button to the webpage and launch it when the user click on it (a set of image that contains the ASL alphabet)
Related issue : #138
=> feat: Add a web link to the ASL alphabet on the practice screen and format files

app/src/androidTest/java/com/github/se/signify/ui/screens/home/QuestScreenTest.kt, app/src/main/java/com/github/se/signify/model/quest/Quest.kt, app/src/main/java/com/github/se/signify/model/quest/QuestRepository.kt, app/src/main/java/com/github/se/signify/model/quest/QuestRepositoryFireStore.kt, app/src/main/java/com/github/se/signify/model/quest/QuestViewModel.kt, app/src/main/java/com/github/se/signify/ui/screens/home/QuestScreen.kt, app/src/test/java/com/github/se/signify/model/quest/QuestRepositoryFirestoreTest.kt, app/src/test/java/com/github/se/signify/model/quest/QuestViewModelTest.kt
**Title:** Implement and test the Daily Quest Screen
This pull request introduces a comprehensive implementation of the Daily Quest feature, including the UI screen, repository functionality, the view model and extensive test coverage.
1. **Daily Quest Screen (Jetpack Compose)**:
- **`QuestScreen`**: Implemented a Jetpack Compose UI screen that displays the daily quest with a title, description, and an actionable button.
- **`QuestBox`**: Created a composable that displays individual quest information in a clean, accessible format, with a button labeled “I am ready” for user interaction.
- **UI Tests with 80% coverage**: 
- Added UI tests to ensure all elements in the `QuestScreen` and `QuestBox` are correctly displayed, including the header, title, description, and action button.
- …
=> Implement and test the quest screen

app/src/androidTest/java/com/github/se/signify/ui/screens/home/ASLRecognitionTest.kt, app/src/main/java/com/github/se/signify/ui/screens/home/ASLRecognition.kt
The ASLRecognition screen (or practice screen) would fail tests on some devices, since it was implemented using a LazyColumn, and wouldn't load and scroll to the elements it was testing.
I have fixed it by changing the screen to use a Column, like the other screens do.
The tests were changed to scroll to elements on the screen, so they will work on any aspect ratio.
All tests now pass for me locally.
=> Address the ASLRecognition screen's tests failing on some aspect ratios

app/src/androidTest/java/com/github/se/signify/ui/screens/MainActivityTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/profile/MyStatsScreenTest.kt, app/src/main/java/com/github/se/signify/MainActivity.kt, app/src/main/java/com/github/se/signify/ui/screens/profile/MyStatsScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/profile/ProfileScreen.kt
**Summary**
This pull request introduces a new UI screen and its android test, designed to provide users with a comprehensive overview of their statistics. The UI has been developed to look as the figma design. It is link to the issues #144 and #153.
**Changes Made**
- Implemented the UI of the file named `MyStatsScreen.kt` that is coherent with the figma design.
- Created the android test file named `MyStatsScreenTest.kt`.
**Testing**:
- Implemented the Following tests:
- **Display test**: Ensures that all the information is displayed correctly.
- **Scroll test**: Verifies that the box with the letter learned can be scrolled horizontally.
- **Back Navigation Test**: Confirms that clicking the back button triggers the expected navigation.
- All tests pass successfully, confirming that the …
=> Stats Screen implementation and test

app/src/androidTest/java/com/github/se/signify/ui/screens/home/HomeScreenTest.kt, app/src/main/java/com/github/se/signify/ui/screens/home/HomeScreen.kt
As proposed by @SaFouNaldo , I have replaced the empty camera preview with a simple button labeled "Try it out!". Tests had to be updated in accordance to this change.
Additionally, the exercise list was changed to be a 1 element tall horizontally scrollable grid.
This PR leaves the screen with a lot of new blank space, which we'll need to fill somehow.
I am not convinced with these changes, and suggest we explore new layouts for the home screen and its exercises.
Still, it shouldn't hurt to merge this for now.
=> Replace the home screen's camera preview box with a button

gradle/libs.versions.toml
SonarCloud's test coverage in the CI has been showing constant 0% coverage for all PRs since my refactor to `gradle/libs.version.toml` in [this PR](https://github.com/Signify-epfl/signify-app/pull/160/files#diff-697f70cdd88ba88fe77eebda60c7e143f6ad1286bca75017421e93ad84fb87df).
@ziyadbagh thinks this might be due to removing sonar from the version catalog `gradle/libs.version.toml`. I have reverted this change to test whether this was indeed the issue.
I suggest we merge this PR to test whether this fixes the CI, and roll it back if it doesn't.
If this does not fix the issue, since I don't think I have admin access on SonarCloud, I will probably need assistance from @SaFouNaldo .
=> Revert removal of sonar plugin from version catalog

app/src/main/java/com/github/se/signify/model/user/UserRepository.kt, app/src/main/java/com/github/se/signify/model/user/UserRepositoryFireStore.kt, app/src/main/java/com/github/se/signify/model/user/UserViewModel.kt, app/src/test/java/com/github/se/signify/model/user/UserRepositoryFireStoreTest.kt, app/src/test/java/com/github/se/signify/model/user/UserViewModelTest.kt
This pull request introduces two new functions, getProfilePictureUrl and updateProfilePictureUrl, to manage profile picture operations in the UserRepository and its implementation UserRepositoryFireStore. Additionally, corresponding tests have been added to ensure these functions work as expected.
**Changes:**
Code Enhancements:
- Added getProfilePictureUrl function to retrieve the user's profile picture URL.
- Added updateProfilePictureUrl function to update the user's profile picture URL.
- Updated the UserRepository interface to include these two new methods.
- Integrated the new methods into the UserViewModel for seamless interaction.
**Tests Added:**
- Created unit tests for getProfilePictureUrl and updateProfilePictureUrl : 
- Verified successful retrieval of profile picture URL.
- …
=> Add getProfilePictureUrl and updateProfilePictureUrl Functions with Corresponding Tests

app/src/androidTest/java/com/github/se/signify/ui/screens/profile/SettingsScreenTest.kt, app/src/main/java/com/github/se/signify/ui/screens/profile/SettingsScreen.kt
This pull request introduces the functionality to manage profile pictures in the SettingsScreen. Users can now:
- Choose a profile picture from their gallery.
- Delete the profile picture, reverting to a default placeholder.
__________
**New Components :** 
_Composable: UserProfilePicture_
- Displays the user's profile picture if available or a default placeholder when no image is set.
- Supports interaction for editing or deleting the profile picture.
_Function: uriToFile_
- Converts a Uri (e.g., from the gallery) into a File stored in the app's cache directory.
- Handles exceptions and ensures invalid URIs return null.
**Tests Added**
To ensure the reliability and accuracy of the new features, I implemented tests for all the new code, specially the function uriToFile. 
Finally we have a …
=> New feature : update profile picture 

app/src/main/AndroidManifest.xml
I updated the `AndroidManifest.xml` to lock `MainActivity` to portrait orientation.
- Set `android:screenOrientation="portrait"` for `MainActivity` to restrict it to portrait mode.
- Added `tools:ignore="LockedOrientationActivity"` to suppress Lint warnings about locking the screen orientation. This suppression helps keep the IDE free from unnecessary warnings while maintaining the desired orientation behavior.
=> Lock the app to portrait mode

.github/workflows/CI.yaml
- The app requires two large model files, RFC_model_ir9_opset19.onnx (116 MB) and hand_landmarker.task (7.8 MB), for hand detection functionality. When building the APK locally, the model files were correctly included, and the app worked as expected. However, when building the APK in the CI environment, the models were either missing or corrupted, causing the app's hand detection feature to fail.
To resolve this issue, I:
- Configured Git LFS for Large Files: Added RFC_model_ir9_opset19.onnx and hand_landmarker.task to Git LFS due to their large sizes, ensuring they could be properly managed and stored in the repository without exceeding Git's standard file size limits.
- Updated CI Pipeline to Handle Git LFS Files:
- Installed Git LFS in the CI environment to ensure that large files are …
=> fix: for Including Large Model Files in CI-Built APK

app/src/androidTest/java/com/github/se/signify/ui/screens/MainActivityTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/UtilsTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/home/ASLRecognitionTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/home/ExerciseScreenEasyTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/home/ExerciseScreenHardTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/home/HandLandMarkImplementationInstrumentedTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/home/QuestScreenTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/profile/FriendsListScreenTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/profile/ProfileScreenTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/profile/SettingsScreenTest.kt, app/src/main/java/com/github/se/signify/MainActivity.kt, app/src/main/java/com/github/se/signify/model/challenge/ChallengeViewModel.kt, app/src/main/java/com/github/se/signify/model/di/AppDependencyProvider.kt, app/src/main/java/com/github/se/signify/model/di/DependencyProvider.kt, app/src/main/java/com/github/se/signify/model/hand/HandLandMarkImplementation.kt, app/src/main/java/com/github/se/signify/model/quest/QuestViewModel.kt, app/src/main/java/com/github/se/signify/model/user/UserViewModel.kt, app/src/main/java/com/github/se/signify/ui/screens/challenge/CreateAChallengeScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/challenge/NewChallengeScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/home/QuestScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/profile/FriendsListScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/profile/ProfileScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/profile/SettingsScreen.kt, app/src/test/java/com/github/se/signify/model/di/MockDependencyProvider.kt
We need to write end-to-end tests before this week's milestone. To achieve this, we must mock all internet or account related backend logic. This is done using dependency injection, where a mock class replaces default implementations of backend logic in a screen's parameters.
Clearing up space for dependency injection will also enable more in depth integration tests. Helping improve coverage for those difficult connectivity related classes.
This PR only aims to make space for future changes. It should not affect the app's functionality in any way.
I would still recommend reviewers to thouroughly check the app's logic, as I might have inadvertently broken something.
`MainActivity's` `SignifyAppPreview` now takes a `DependencyProvider` parameter. This dependency provider is a singleton …
=> Setup dependency injection for mocks

app/src/androidTest/java/com/github/se/signify/ui/screens/UtilsTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/home/HomeScreenTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/profile/FriendsListScreenTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/profile/MyStatsScreenTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/profile/ProfileScreenTest.kt, app/src/main/java/com/github/se/signify/model/user/SaveUserToFireStore.kt, app/src/main/java/com/github/se/signify/model/user/User.kt, app/src/main/java/com/github/se/signify/model/user/UserRepository.kt, app/src/main/java/com/github/se/signify/model/user/UserRepositoryFireStore.kt, app/src/main/java/com/github/se/signify/model/user/UserViewModel.kt, app/src/main/java/com/github/se/signify/ui/Utils.kt, app/src/main/java/com/github/se/signify/ui/screens/home/HomeScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/profile/FriendsListScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/profile/MyStatsScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/profile/ProfileScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/profile/SettingsScreen.kt, app/src/test/java/com/github/se/signify/model/user/UserRepositoryFireStoreTest.kt, app/src/test/java/com/github/se/signify/model/user/UserViewModelTest.kt
_____
**Description:**
This PR introduces the **streak feature**, allowing users to track:
1. The number of consecutive days they have been connected to the application.
2. The highest streak score (not yet implemented in the UI but planned for future integration, possibly in the StatsScreen).
The following changes have been made:
- **Added functionality:**
- `updateStreak` and `getStreak` functions in the `UserViewModel` to handle streak calculation and retrieval.
- **UI updates:**
- Displayed the updated streak value in the `ProfileScreen`.
- Adapted the text to handle singular cases (e.g., "1 day") in the `Utils` file.
- Changed the streak type to `Long` for compatibility with Firestore's number representation.
- **Testing:**
- Added unit tests for `updateStreak` and `getStreak` to …
=> Streaks implementation

app/src/androidTest/java/com/github/se/signify/ui/screens/challenge/CreateAChallengeScreenTest.kt, app/src/main/java/com/github/se/signify/model/challenge/ChallengeRepository.kt, app/src/main/java/com/github/se/signify/model/challenge/ChallengeRepositoryFireStore.kt, app/src/main/java/com/github/se/signify/model/challenge/ChallengeViewModel.kt, app/src/main/java/com/github/se/signify/ui/Utils.kt, app/src/main/java/com/github/se/signify/ui/screens/challenge/CreateAChallengeScreen.kt, app/src/test/java/com/github/se/signify/model/challenge/ChallengeRepositoryFireStoreTest.kt, app/src/test/java/com/github/se/signify/model/challenge/ChallengeViewModelTest.kt
I've refactored the challenge creation screen as best I could.
- `CreateAChallenge.kt` has been refactored to use as many common elements from Utils.kt as possible.
- Hardcoded screen colors have been changed to use the correct theme colors.
- Challenge modes, previously encoded as `String`s are now an `enum`.
- Challenge mode selection logic is no longer hardcoded and can now accomodate new modes.
I've had to add an `enabled` parameter to a common button in `Utils.kt` to conserve the functionality of a button in the challenge creation screen. This added parameter has a default value that should stop it from affecting previous uses of the button.
Here are a few screenshots of the updated screen.
This screen still feels a little dull. There is definitely space for additions.
There is also …
=> Update the challenge creation screen to use common elements from Utils.kt

app/src/androidTest/java/com/github/se/signify/ui/screens/BottomBarNavigationTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/MainActivityTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/UtilsTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/challenge/ChallengeScreenTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/challenge/NewChallengeScreenTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/home/ASLRecognitionTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/home/HomeScreenTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/home/QuestScreenTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/profile/ProfileScreenTest.kt, app/src/main/java/com/github/se/signify/MainActivity.kt, app/src/main/java/com/github/se/signify/ui/Utils.kt, app/src/main/java/com/github/se/signify/ui/navigation/BottomNavigationMenu.kt, app/src/main/java/com/github/se/signify/ui/navigation/Route.kt, app/src/main/java/com/github/se/signify/ui/navigation/Screen.kt, app/src/main/java/com/github/se/signify/ui/screens/challenge/ChallengeScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/challenge/NewChallengeScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/home/ASLRecognition.kt, app/src/main/java/com/github/se/signify/ui/screens/home/HomeScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/profile/ProfileScreen.kt
This PR is about refactoring the navigation system to standardize the use of `Route` and `Screen`:
- `Route` is now used exclusively for main screens:
- Welcome, Authentication, Home, Profile, and Challenge screens.
- `Screen` is used for both main screens and annex screens (accessible from main screens).
- Ensure the navigation still works as before and the tests pass.
- Link to the issue #252 .
Additionally:
- Added missing tests for the bottom navigation menu across different screens and utilities to ensure consistent behavior.
=> refactor: navigation and add missing tests

app/src/androidTest/java/com/github/se/signify/ui/screens/home/HomeScreenTest.kt, app/src/main/java/com/github/se/signify/ui/screens/home/HomeScreen.kt
- This PR enhances the LetterDictionary component within the HomeScreen by adding support for horizontal scrolling via swipe gestures in the pager, alongside the existing button-based navigation. The implementation ensures seamless navigation between letters in both directions (left and right) using the pager.
The following updates have been made:
- There was a problem with navigating to the questScreen after the PR of #253 that was not catched up, I changed that accordingly.
- Added swipe-based scrolling logic for the LetterDictionary pager.
Users can now swipe through letters in addition to using the LetterDictionaryForward and LetterDictionaryBack buttons.
Note: Scrolling directly from A to Z (or Z to A) via swipe gestures is not implemented. Button navigation still allows wrapping …
=> feat: add the scrolling logic of a pager in the LetterDictionary in HomeScreen and updating/wrinting tests accordingly

README.md, app/src/androidTest/java/com/github/se/signify/ui/screens/challenge/CreateAChallengeScreenTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/challenge/NewChallengeScreenTest.kt, app/src/main/java/com/github/se/signify/model/challenge/MockChallengeRepository.kt, app/src/test/java/com/github/se/signify/model/challenge/ChallengeViewModelTest.kt, app/src/test/java/com/github/se/signify/model/challenge/MockChallengeRepositoryTest.kt
---
This PR introduces a new `MockChallengeRepository` to streamline testing of components that rely on `ChallengeRepository`. Additionally, it refactors the tests for `ChallengeViewModel`,`CreateChallengeScreen` and `NewChallengeScreen` to use this mock. The aim is to simplify testing by centralizing ChallengeRepository logic in a reusable mock.
---
1. **Created `MockChallengeRepository`**:
- Simulates the behavior of `ChallengeRepository` with in-memory storage for challenges.
- Supports toggling success and failure scenarios using `shouldSucceed` and `exceptionToThrow`.
- Includes helper methods like `setChallenges` and `getChallenges` for test setup and verification.
2. **Created `MockChallengeRepositoryTest`**:
- Testing of the various functions of the mock.
3. **Refactored Tests**: …
=> 261 mock the challenge repository

app/src/androidTest/java/com/github/se/signify/ui/screens/profile/FriendsListScreenTest.kt, app/src/main/java/com/github/se/signify/ui/screens/profile/FriendsListScreen.kt, app/src/main/res/values/strings.xml
This pull request addresses the points we discussed during the meeting and includes the following updates:
1. **Search Bar Behavior**:
- After searching for a user, the search bar is now automatically cleared to improve user experience.
2. **Confirmation Dialog for Removing Friends**:
- A dialog has been added to confirm the user's intention before removing a friend. This prevents accidental removals and ensures clarity in user actions.
3. **Simplification of Friend Details**:
- The profile picture and user name were removed from the screen to avoid confusion with the profile screen, ensuring a clearer separation of concerns.
4. **Separation of Lists**:
- Friends and friend requests are now displayed in two separate sections, toggled by buttons. Each list occupies the whole screen when …
=> Refactor friends list screen

app/src/androidTest/java/com/github/se/signify/ui/screens/home/ASLRecognitionTest.kt, app/src/androidTest/java/end2end/MainToASLRecognitionTest.kt, app/src/main/java/com/github/se/signify/ui/screens/home/ASLRecognition.kt, app/src/main/java/com/github/se/signify/ui/screens/home/HomeScreen.kt, app/src/main/res/values/strings.xml
This PR addresses three changes in the application:
- Updated the logic for scrolling in the LetterDictionary component to directly scroll to the target item in the LazyColumn using scrollToItem instead of animateScrollToItem.
This ensures a smoother and more predictable navigation experience, preventing intermediate stops at unintended items (e.g., SignTipBox_C).
- Changed the text of the "Try it out" button to "Try hand signs here!" for better clarity and user engagement.
- Refactor ASLRecognition using MainScreenScaffold, helpText is modularized using res/values/strings.xml that contains the relevant text.
- Update test that checks if the BackButton is correctly displayed and add a new test that verifies if the button calls goBack()
=> fix: the set of letters F-G-H the scroll is working

app/src/main/java/com/github/se/signify/model/challenge/Challenge.kt, app/src/main/java/com/github/se/signify/model/challenge/ChallengeRepository.kt, app/src/main/java/com/github/se/signify/model/challenge/ChallengeRepositoryFireStore.kt, app/src/main/java/com/github/se/signify/model/challenge/MockChallengeRepository.kt, app/src/test/java/com/github/se/signify/model/challenge/ChallengeRepositoryFireStoreTest.kt, app/src/test/java/com/github/se/signify/model/challenge/ChallengeTest.kt, app/src/test/java/com/github/se/signify/model/challenge/MockChallengeRepositoryTest.kt
This Pull Request implements a new challenge feature in the Signify app — the *Chrono Challenge*. The changes include modifications to the database. The goal is to provide users with an engaging experience where they complete challenges against friends in the minimum time possible.
- Added new fields to the `Challenge` class:
- Track player-specific round completion (`player1RoundCompleted`, `player2RoundCompleted`).
- Track player times (`player1Times`, `player2Times`) for each round, recorded in milliseconds.
- Updated `ChallengeRepository` and `ChallengeRepositoryFirestore` to handle:
- Creation, update, and retrieval of challenge states.
- Saving player times and tracking each round's completion status.
- Proper calculation and display of the player's total time after all rounds are …
=> Refactor challenge database with its tests

app/src/androidTest/java/com/github/se/signify/ui/screens/challenge/ChronoChallengeGameScreenTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/challenge/CreateAChallengeScreenTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/challenge/NewChallengeScreenTest.kt, app/src/main/java/com/github/se/signify/MainActivity.kt, app/src/main/java/com/github/se/signify/ui/navigation/NavigationActions.kt, app/src/main/java/com/github/se/signify/ui/navigation/Screen.kt, app/src/main/java/com/github/se/signify/ui/screens/challenge/ChronoChallengeGameScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/challenge/CreateAChallengeScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/challenge/NewChallengeScreen.kt
This Pull Request implements a new challenge feature in the Signify app — the *Chrono Challenge*. The changes include  creation of new screens, and enhancement of existing screens to support this new gameplay. The goal is to provide users with an engaging experience where they complete challenges against friends in the minimum time possible.
The *Chrono Challenge* mode is a new competitive feature where players are tasked with completing three ASL words as quickly as possible. Here are the key details:
- Players can play their three rounds at their convenience — there is no specific order in which they must play compared to their opponent.
- Once a player completes all three rounds, they wait for their opponent to finish before viewing the final challenge results.
- The goal is to …
=> Playable Chrono Game UI

app/src/androidTest/java/com/github/se/signify/ui/screens/challenge/ChallengeHistoryScreenTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/home/FeedbackScreenTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/home/QuizScreenTest.kt, app/src/main/java/com/github/se/signify/model/feedback/Feedback.kt, app/src/main/java/com/github/se/signify/ui/Utils.kt, app/src/main/java/com/github/se/signify/ui/screens/challenge/ChallengeHistoryScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/home/FeedbackScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/home/QuizScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/profile/MyStatsScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/profile/ProfileScreen.kt
The changes made in this PR are mostly code refactoring and don't affect the behaviour of our app.
Related issues: #315 , #316 .
- `QuizScreen` and `FeedbackScreen` use `AnnexScreenScaffold()` from Utils.kt now
- `ChallengeHistoryScreen`, `FeedbackScreen`, `MyStatsScreen` and `ProfileScreen` have their viewModels as a val and are not anymore in the list of argument.
- Color change in Utils.kt for the `topBar()` and remove useless argument in the `ScreenColumn()`
- ASLRecognition might need change in its design to help user doing the sign they want.
- QuestScreen will have a new design and implementation.
- FriendsListScreen is tested with a given viewModel, if we want to change it, we have to addapt the test.
- There is no added test for this part as the main changes are on the use of …
=> Screen refactor for common element and uniformity

app/src/main/java/com/github/se/signify/model/user/MockUserRepository.kt, app/src/main/java/com/github/se/signify/model/user/UserRepository.kt, app/src/main/java/com/github/se/signify/model/user/UserRepositoryFireStore.kt, app/src/test/java/com/github/se/signify/model/user/MockUserRepositoryTest.kt
A new `MockUserRepository.kt` fake implements the interface `UserRepository.kt`. This fake should be used in testing to replace the `UserRepositoryFireStore.kt` class. This new mock almost perfectly matches the behavior of `UserRepositoryFireStore.kt` used in production.
Basic tests for the class achieve perfect line coverage, barring a single check that should not exist. 
There is always space for some more complex tests. But I don't think this mock carries too much risk of complex failure cases.
As mentioned above, the mock requires a weird check in `getStreak()` due to an inconsistency in existing code. I've marked this as a task in the scrum board.
The interface `UserRepository.kt` defines an `updateStreak()` method. With no documentation on it, and questionable design, I could not …
=> Mock the user repository

app/src/main/java/com/github/se/signify/model/stats/StatsViewModel.kt, app/src/test/java/com/github/se/signify/model/stats/StatsViewModelTest.kt
---
**Introduce StateFlow for update call results in `StatsViewModel` and Enhance Error Handling**
After a PR in which the `ExerciseScreen` was improved and now makes an `updateStats` call to the ViewModel, I noticed that it didn't have access to the result of this operation—specifically whether it failed or succeeded. It assumed success and reset its state automatically.
This PR introduces a `StateFlow` (`updateStatsEvent`) in `StatsViewModel` that screens can observe to react accordingly. For example, they can display a loading indicator or handle success/failure appropriately. Additionally, a `resetUpdateStatsEvent` function is added to allow screens to reset the state explicitly.
- Added `updateStatsEvent` as a `StateFlow` in `StatsViewModel`.
- Added `resetUpdateStatsEvent` function …
=> Add updateStatsEvent StateFlow to StatsViewModel

app/src/androidTest/java/com/github/se/signify/ui/screens/LoginScreenTest.kt
**Description:**  
I researched online using GPT and StackOverflow but couldn't find any relevant solutions. I also asked around, and it seems many people have experienced this test failing intermittently. As a result, we have decided to delete the `titleAndButtonAreCorrectlyDisplayed()` test. Additionally, the `composeTestRule.setContent { LoginScreen(navigationActions, {}) }` setup has been moved to the `@Before` method for better structure.
=> Remove Failing Login Test

app/src/androidTest/java/com/github/se/signify/ui/screens/profile/SettingsScreenTest.kt, app/src/main/java/com/github/se/signify/model/common/user/FirestoreUserRepository.kt, app/src/main/java/com/github/se/signify/ui/screens/profile/SettingsScreen.kt, app/src/test/java/com/github/se/signify/model/common/user/FirestoreUserRepositoryTest.kt
This PR addresses two separate issues:
1. Updates the **Settings Screen** to align its design with the Figma prototype, including adding the switch button.
2. Standardizes failure handling across methods in `UserRepository` to ensure consistent behavior when a user is not found.
Although these issues are unrelated, both required minimal changes, and given the number of open PRs, I opted to include them in a single PR to reduce overhead.
---
- Moved the options section below the profile editing section to match the Figma prototype.
- Added the **switch button** as defined to the Figma design.
- Removed the unused `NotImplementedYet` box.
- Updated all methods to call `onFailure()` when a user is not found.
- Updated corresponding tests to reflect the new behavior.
- Ensured uniform failure …
=> Fix inconsistencies

app/src/androidTest/java/com/github/se/signify/ui/common/ScreensTest.kt, app/src/main/java/com/github/se/signify/ui/common/Screens.kt, app/src/main/java/com/github/se/signify/ui/screens/auth/UnauthenticatedScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/challenge/ChallengeScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/home/HomeScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/profile/ProfileScreen.kt
The navigation bar no longer highlights the current destination.
It turns out this issue was deeper than just changing some colors.
- `MainScreenScaffold()` now takes a screen's `TopLevelDestination` to determine which bottom bar item to highlight.
- The bottom bar now correctly highlights the current destination.
Note, the unauthenticated screen counts as "home" for now.
- Some minor visual adjustments to `BottomBar()` were made to match its design on Figma.
Here's the new look of the bottom bar,
=> Fix navigation bar highlighting

app/src/main/java/com/github/se/signify/model/common/user/FirestoreUserRepository.kt, app/src/main/java/com/github/se/signify/model/common/user/MockUserRepository.kt, app/src/main/java/com/github/se/signify/model/common/user/SaveUserToFirestore.kt, app/src/main/java/com/github/se/signify/model/common/user/UserViewModel.kt, app/src/test/java/com/github/se/signify/model/common/user/FirestoreUserRepositoryTest.kt, app/src/test/java/com/github/se/signify/model/common/user/MockUserRepositoryTest.kt, app/src/test/java/com/github/se/signify/model/common/user/SaveUserToFirestoreTest.kt
This pull request addresses an issue where parts of the code defaulted to `"unknown"` when a user was not logged in. This behavior caused an `"unknown"` user to be created in the database, leading to crashes when attempting to add the `"unknown"` account as a friend. The following changes have been made:
1. **Removed all uses of the `"unknown"` default value**:
- Operations now fail instead of defaulting to `"unknown"`.
- Proper error handling is implemented to handle missing or invalid user data.
2. **Ensured invalid `userId`s are handled safely**:
- Introduced checks for null, blank, or invalid `userId`s.
- Improved error logging and flow to prevent crashes.
- **`FirestoreUserRepository.kt`**: Updated `getUserName` to remove `"unknown"` fallback and handle errors properly.
- …
=> Fix friends crash

app/src/androidTest/java/com/github/se/signify/ui/common/ScreensTest.kt, app/src/main/java/com/github/se/signify/model/navigation/NavigationActions.kt, app/src/main/java/com/github/se/signify/ui/common/Screens.kt, app/src/test/java/com/github/se/signify/model/navigation/NavigationActionsTest.kt
- The bottom navigation bar now disables the current destination.
- `NavigationActions` now prevent navigating to the current screen.
Regression tests were added to `Screens.BottomNavigationMenu()`.
I didn't manage to test the guard clause added to `NavigationActions` because `NavController` is really difficult to mock.
=> Fix blinking when navigating to the current screen

app/src/androidTest/java/com/github/se/signify/ui/screens/tutorial/ProvideElementPositionsTest.kt, app/src/main/java/com/github/se/signify/MainActivity.kt, app/src/main/java/com/github/se/signify/ui/screens/tutorial/ElementPosition.kt, app/src/main/java/com/github/se/signify/ui/screens/tutorial/TutorialOverlay.kt, app/src/main/java/com/github/se/signify/ui/screens/tutorial/TutorialScreen.kt
**Description:**
This PR includes the following changes to improve the positioning and layout of the tutorial across all devices:
1. **Refactored `ElementPosition.kt`:**  
- Updated the logic to use `positionInRoot()` instead of `positionInWindow()` to ensure the tutorial is properly centered on all devices, regardless of system-level offsets (e.g., status bar or navigation bar).
2. **Updated Tests in `ProvideElementPositionsTest.kt`:**  
- Adjusted the unit tests to align with the new logic using `positionInRoot()`. The mocks and assertions now account for the updated positioning behavior.
3. **Reduced Bottom Padding in `TutorialOverlay.kt`:**  
- Reduced the bottom padding of the tutorial message for a more balanced and visually appealing layout.
4. **Modified Skip Button Placement in …
=> Fix the tutorial to be centered for all the devices sizes

app/src/main/java/com/github/se/signify/MainActivity.kt
This PR resolves an issue where the app would default to English at launch, regardless of the saved language preference.  
1. **Fixed SharedPreferences Edit Call:**  
- Corrected the `sharedPreferencesLanguage.edit()` call to properly update the `prefKeyLanguage`. This ensures the `savedLanguage` is correctly saved when changed through the settings screen.  
2. **Applied Language Preference at Launch:**  
- Added a call to the `updateLanguage` function in `onCreate` to ensure the app applies the saved language preference (French/English) on launch.  
- Users' language preferences are now correctly persisted and applied across sessions.  
- Verified that the language preference is correctly applied at launch.  
- Tested switching between French and English via the settings screen and …
=> Correct shared preference for language

app/src/main/java/com/github/se/signify/model/navigation/NavigationActions.kt
This PR addresses the issue with the back navigation button where rapid double-taps could cause unintended behavior. The following changes have been made:  
- Added a debounce mechanism to throttle back actions, preventing multiple triggers within 500ms.  
- Updated navigation logic to clear the entire back stack by setting the new route as the root.
- Logged a message when there are no more screens to pop in the navigation stack.  
These changes improve navigation reliability and user experience.
=> Fix back navigation to prevent rapid double-tap actions

app/src/androidTest/java/com/github/se/signify/ui/screens/profile/SettingsScreenTest.kt, app/src/main/java/com/github/se/signify/ui/screens/profile/SettingsScreen.kt, app/src/main/res/values-fr/strings.xml, app/src/main/res/values/strings.xml
This PR removes the "NA" option from the language selection dropdown menu. The corresponding test for the "NA" option has also been deleted, as it is no longer relevant.
=> Remove "NA" Option from language dropdown menu

app/src/main/java/com/github/se/signify/ui/common/Buttons.kt, app/src/main/java/com/github/se/signify/ui/common/Practice.kt, app/src/main/java/com/github/se/signify/ui/screens/challenge/CreateAChallengeScreen.kt
All outlines were removed from buttons both in code and on Figma.
The `CreateAChallengeScreen`s mode picker dialog still looks weird. I wasted some time trying to change it's background to an opaque color, but didn't manage to set it to white, because the `@Composable` acts weird.  I'll let someone else try to fix it, if it is deemed necessary.
=> Remove button outlines

app/src/androidTest/java/com/github/se/signify/ui/screens/challenge/ChallengeHistoryScreenTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/challenge/SprintChallengeGameScreenTest.kt, app/src/main/java/com/github/se/signify/MainActivity.kt, app/src/main/java/com/github/se/signify/model/challenge/Challenge.kt, app/src/main/java/com/github/se/signify/model/challenge/FirestoreChallengeRepository.kt, app/src/main/java/com/github/se/signify/model/navigation/Screen.kt, app/src/main/java/com/github/se/signify/ui/screens/challenge/ChallengeHistoryScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/challenge/NewChallengeScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/challenge/SprintChallengeGameScreen.kt
This PR introduces a **Sprint Mode** in the challenge feature, where two players compete in a **Best of 3 (BO3)** format. The goal of this mode is for players to input as many words as possible within **1 minute per round**. The winner is determined based on the total number of words completed across all three rounds.  
**Key Features:**  
1. **Sprint Challenge Gameplay**:  
- Each round lasts for 1 minute.  
- The player who completes the most words after 3 rounds wins the challenge.  
2. **Automatic Challenge Cleanup**:  
- Once the second player completes their rounds, the challenge is automatically removed from the **ongoing challenges**.  
- Results are accessible in the **History Screen** for both players.  
3. **Database Updates**:  
- Added two new fields to the `challenge` …
=> Sprint Mode 

app/src/main/java/com/github/se/signify/MainActivity.kt, app/src/main/java/com/github/se/signify/model/navigation/NavigationActions.kt, app/src/main/java/com/github/se/signify/ui/screens/auth/LoginScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/auth/UnauthenticatedScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/tutorial/TutorialScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/welcome/WelcomeScreen.kt, app/src/test/java/com/github/se/signify/model/navigation/NavigationActionsTest.kt
A recent change stopped the user from leaving the `UnauthenticatedScreen()`.
Additionally, a bug remains where the user can press the system "back" button to navigate back to the login, welcome, or tutorial screens, if they do so before navigating to any other screen.
The `UnauthenticatedScreen()` is now an `AnnexScreen()`, which probably fits it better, and fixes the first bug above.
All instances of `navigationActions.navigateTo(Screen.HOME)` were replaced with `navigationActions.navigateTo(TopLevelDestinations.HOME)`. This fixes the the second bug.
SonarCloud computes low test coverage on this PR, yet I've only changed lines that were already difficult to test. Also, this PR is only +23 lines.
I suggest you just ignore the report.
=> Change the unauthenticated screen to be an annex screen

app/src/androidTest/java/com/github/se/signify/ui/screens/challenge/SprintChallengeGameScreenTest.kt, app/src/main/java/com/github/se/signify/ui/screens/challenge/NewChallengeScreen.kt, app/src/main/java/com/github/se/signify/ui/screens/challenge/SprintChallengeGameScreen.kt
**Summary:**
This pull request introduces enhancements to the Sprint Mode and resolves a critical bug affecting stat incrementing and timer functionality.
---
**Key Changes:**
1. **Skip Button Implementation:**
- Added a **Skip** button to the Sprint Mode.
- The button allows players to skip the current word.
- When pressed:
- A new word is displayed.
- 5 seconds are deducted from the remaining time.
- The word counter is not incremented.
- The button is automatically disabled when the timer reaches 0 to prevent negative time.
2. **Timer Logic Update:**
- Added a condition to ensure that the timer cannot go below **0 seconds**.
- This prevents scenarios where spamming the Skip button could result in a negative timer value.
3. **Stat Increment Bug Fix:**
- Fixed a bug where stats (e.g., …
=> Skip button in sprint mode 

app/src/main/java/com/github/se/signify/ui/common/Profile.kt
- Added an outline to the profile picture in the app to enhance its visibility and design consistency.
- The outline is styled using the primary color of the application for a cohesive look.
- The implementation ensures both user-uploaded images and default placeholder icons have the outline applied.
- Updated the corresponding Figma design to reflect this change for future reference and alignment with the app's UI.
- Modified the `ProfilePicture` composable to include an outlined stroke around the profile picture.
- Synchronized the updated profile picture style with the Figma design for team consistency.
This update ensures consistency across the app and design documentation, enhancing the user experience and alignment with the visual design.
=> Add outline to the profile picture and update figma

app/src/androidTest/java/com/github/se/signify/ui/screens/challenge/ChronoChallengeGameScreenTest.kt, app/src/main/java/com/github/se/signify/ui/screens/challenge/ChronoChallengeGameScreen.kt
This PR resolves a bug in the **Chrono Challenge mode**, ensuring that the word chosen for the user depends on the number of rounds they have completed. This fix allows both players to progress through their respective rounds synchronously, improving the gameplay experience and eliminating inconsistencies in word selection.
- **Bug Fix: Word Selection Logic**
- Added a helper function `findNextIndex()` to determine the next incomplete round for the current user based on their progress.
- Updated the logic to select the current word using `findNextIndex()`, ensuring the word corresponds to the user's current round.
- Guarded against invalid indexes to prevent crashes (e.g., when all rounds are completed or if the user is not recognized).
- Ensured the game now correctly handles users …
=> Resolve chrono mode rounds choosing

app/src/androidTest/java/com/github/se/signify/ui/screens/challenge/SprintChallengeGameScreenTest.kt, app/src/androidTest/java/com/github/se/signify/ui/screens/home/QuizScreenTest.kt, app/src/main/java/com/github/se/signify/model/navigation/Screen.kt, app/src/main/java/com/github/se/signify/ui/screens/home/QuizScreen.kt
This PR accomplishes two key improvements:
1. **Authentication for Quiz Screen:** Added authentication requirements to the Quiz screen, ensuring only authenticated users can access it. Consequently, only the Home screen remains accessible in offline mode.
2. **Quiz Loading Fix:** Fixed the issue where the Quiz screen initially displayed an unavailable quiz by ensuring quizzes are properly fetched from the database and are never null upon first launch.
=> Enforce Quiz Authentication & Fix Initial Loading Issue

app/src/androidTest/java/com/github/se/signify/ui/screens/challenge/ChallengeScreenTest.kt, app/src/main/java/com/github/se/signify/ui/screens/challenge/ChallengeScreen.kt, app/src/main/res/values-fr/strings.xml, app/src/main/res/values/strings.xml
This PR introduces a new **Info Button** to the `ChallengeScreen`, providing users with detailed information about how challenges work in the app. The Info button opens a popup dialog explaining the two challenge modes (Sprint and Chrono) and where results can be viewed. This enhancement improves the user experience by offering clarity and guidance.
---
1. **Info Button Added:**
- Positioned at the bottom of the Ongoing Challenges section.
- Displays a popup when clicked.
2. **Info Dialog:**
- Contains the following explanatory text:
- **Sprint Mode:** Best-of-3, where players type the maximum number of words in one minute.
- **Chrono Mode:** Best-of-3, where players type a word as fast as possible in three rounds.
- Results are displayed in the **Challenge History Screen** (top-left …
=> Challenges info for user
